"""add new columns

Revision ID: 6a47b4f58239
Revises: fc59053f4f1f
Create Date: 2024-12-29 10:43:01.694862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a47b4f58239'
down_revision: Union[str, None] = 'fc59053f4f1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_auto_login', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_auto_login')
    # ### end Alembic commands ###
