"""Fix foreign_keys in Chat and User models

Revision ID: fc59053f4f1f
Revises: 14b8969568e7
Create Date: 2024-12-23 21:51:57.317142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc59053f4f1f'
down_revision: Union[str, None] = '14b8969568e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
